/**
 * Export utilities for Prompt Optimizer
 * Supports Markdown and JSON export formats
 */

interface RoundData {
  round: number;
  status: string;
  analysis?: {
    clarity: number;
    specificity: number;
    context: number;
    structure: number;
    outputFormat: number;
  };
  weaknesses?: string[];
  improvements?: string[];
  optimizedPrompt?: string;
  overallScore?: number;
}

export interface ExportData {
  original: string;
  final: string;
  rounds: RoundData[];
  finalScore?: number;
  timestamp: string;
  totalRounds: number;
}

/**
 * Download a file to user's browser
 */
function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export optimization results as Markdown
 */
export function exportToMarkdown(data: ExportData): void {
  const { original, final, rounds, finalScore, timestamp, totalRounds } = data;
  
  let markdown = `# Prompt Optimization Results\n\n`;
  markdown += `**Generated**: ${new Date(timestamp).toLocaleString('de-DE')}\n\n`;
  markdown += `---\n\n`;
  
  // Original vs Final Comparison
  markdown += `## 📝 Prompt Comparison\n\n`;
  markdown += `### Original Prompt\n\`\`\`\n${original}\n\`\`\`\n\n`;
  markdown += `**Length**: ${original.length} characters\n\n`;
  markdown += `### ✅ Optimized Prompt\n\`\`\`\n${final}\n\`\`\`\n\n`;
  markdown += `**Length**: ${final.length} characters (${final.length > original.length ? '+' : ''}${final.length - original.length})\n\n`;
  
  // Summary
  markdown += `---\n\n## 📊 Optimization Summary\n\n`;
  markdown += `- **Total Rounds**: ${totalRounds}\n`;
  markdown += `- **Final Score**: ${finalScore?.toFixed(1) || 'N/A'}/10\n`;
  markdown += `- **Character Change**: ${final.length - original.length} (${Math.round((final.length / original.length - 1) * 100)}%)\n\n`;
  
  // Round Details
  if (rounds.length > 0) {
    markdown += `---\n\n## 🔄 Round-by-Round Details\n\n`;
    
    rounds.forEach((round) => {
      if (round.status !== 'complete') return;
      
      markdown += `### Round ${round.round}`;
      if (round.overallScore) {
        markdown += ` (Score: ${round.overallScore.toFixed(1)}/10)`;
      }
      markdown += `\n\n`;
      
      // Analysis scores
      if (round.analysis) {
        markdown += `**Analysis Scores**:\n`;
        Object.entries(round.analysis).forEach(([key, value]) => {
          markdown += `- ${key}: ${value}/10\n`;
        });
        markdown += `\n`;
      }
      
      // Weaknesses
      if (round.weaknesses && round.weaknesses.length > 0) {
        markdown += `**⚠️ Identified Weaknesses**:\n`;
        round.weaknesses.forEach((w) => {
          markdown += `- ${w}\n`;
        });
        markdown += `\n`;
      }
      
      // Improvements
      if (round.improvements && round.improvements.length > 0) {
        markdown += `**✅ Improvements Made**:\n`;
        round.improvements.forEach((imp) => {
          markdown += `- ${imp}\n`;
        });
        markdown += `\n`;
      }
      
      markdown += `---\n\n`;
    });
  }
  
  markdown += `\n*Generated by KI-Tricks.com Prompt Optimizer*\n`;
  
  const filename = `prompt-optimization-${new Date().toISOString().slice(0, 19).replace(/:/g, '-')}.md`;
  downloadFile(markdown, filename, 'text/markdown');
}

/**
 * Export optimization results as JSON
 */
export function exportToJSON(data: ExportData): void {
  const jsonString = JSON.stringify(data, null, 2);
  const filename = `prompt-optimization-${new Date().toISOString().slice(0, 19).replace(/:/g, '-')}.json`;
  downloadFile(jsonString, filename, 'application/json');
}